### ISSUE TITLE
Unable to start monitor with already running event loop.

### ISSUE THREAD

**Issue by drankinn** [aio-libs/aiomonitor#162]
I am calling the start_monitor function after initializing the loop and I get the following trace:

``Traceback (most recent call last):
  File "/opt/project/code/framework/taurine/daemon.py", line 142, in start_monitor
    self.monitor = aiomonitor.start_monitor(self.loop, **self.monitor_config)
  File "/usr/local/lib/python3.7/site-packages/aiomonitor/monitor.py", line 411, in start_monitor
    m.start()
  File "/usr/local/lib/python3.7/site-packages/aiomonitor/monitor.py", line 112, in start
    self._host, self._console_port, self._locals, self._loop)
  File "/usr/local/lib/python3.7/site-packages/aiomonitor/utils.py", line 73, in init_console_server
    server = loop.run_until_complete(coro)  # type: Server
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 526, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running``

My use case is that I want to be able to turn monitoring on/off while my python daemon is running.  This is a regression from 0.3.1.
I believe the offending code is in the init_console_server function that tries to do loop.run_until_complete.  this was previously asyncio.run_coroutine_threadsafe

**Comment by jettify** [comment]
Hm, need to think about this, it was never intended to work this way canonical example
```python
import aiomonitor

loop = asyncio.get_event_loop()
with aiomonitor.start_monitor(loop=loop):
    loop.run_forever()
```

where we execute startup in `aiomonitor.start_monitor` synchronously. 

Related to this PR https://github.com/aio-libs/aiomonitor/pull/143/files

**Comment by agronholm** [comment]
Today I tried upgrading aiomonitor from v0.3.1 to v0.4.2 and it fell flat on its face because of this issue.
Why does the latest aiomonitor require control of the event loop's lifecycle? This makes it impossible to integrate into asyncio application frameworks.

**Comment by jettify** [comment]
Will revert https://github.com/aio-libs/aiomonitor/pull/143/files that should fix an issue.

**Comment by jettify** [comment]
@drankinn @agronholm can you please test recent master

**Comment by drankinn** [comment]
@jettify I've tested master today and it looks like you've fixed the issues I was seeing. 
Thanks so much.

**Comment by jettify** [comment]
Thanks for testing! Will do release in day or two.

**Comment by agronholm** [comment]
I can also confirm that it works again as expected.
