### ISSUE TITLE
telnetlib to be deprecated in python3.14

### ISSUE THREAD

**Issue by leftys** [aio-libs/aiomonitor#409]
### Describe the bug

telnetlib, a module aiomonitor is using is to be deprecated in python3.14. here is a similar issue with suggestions for telnetlib replacement: https://github.com/ktbyers/netmiko/issues/3177

### To Reproduce

import aiomonitor from python3.14.0a1

### Expected behavior

no error

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "/usr/src/app/bot/main.py", line 15, in <module>
    from bot.app import App
  File "/usr/src/app/bot/__init__.py", line 1, in <module>
    from bot.app import App
  File "/usr/src/app/bot/app.py", line 20, in <module>
    import aiomonitor
  File "/usr/local/lib/python3.14/site-packages/aiomonitor/__init__.py", line 23, in <module>
    from .monitor import (Monitor, start_monitor,
                          MONITOR_HOST, MONITOR_PORT, CONSOLE_PORT)
  File "/usr/local/lib/python3.14/site-packages/aiomonitor/monitor.py", line 20, in <module>
    from .utils import (_format_stack, cancel_task, task_by_id, console_proxy,
                        init_console_server, close_server, alt_names, all_tasks)
  File "/usr/local/lib/python3.14/site-packages/aiomonitor/utils.py", line 6, in <module>
    import telnetlib
ModuleNotFoundError: No module named 'telnetlib'
```

### Python Version

```console
$ python --version
3.14.0a1
```

### aiomonitor Version

```console
0.4.5
```

### OS

Ubuntu

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
Would you like to take a stab at authoring a pull request?

**Comment by leftys** [comment]
happy to open a PR, but I know little about aiomonitor and telnet, so I am unable to do proper testing

**Comment by jopemachine** [comment]
Since telnetlib was removed in Python 3.13, running `aiomonitor` results in the following error.

```
❯ python -m aiomonitor.cli -p 48100
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/lib/python3.13/site-packages/aiomonitor/cli.py", line 5, in <module>
    from .telnet import TelnetClient
  File "/opt/homebrew/lib/python3.13/site-packages/aiomonitor/telnet.py", line 9, in <module>
    import telnetlib
ModuleNotFoundError: No module named 'telnetlib'
```

**Comment by achimnol** [comment]
There is also [standard-telnetlib](https://pypi.org/p/standard-telnetlib) from [python-deadlib](https://github.com/youknowone/python-deadlib). :wink:
Anyway, I will apply telnetlib3 in favor of a better maintained community version.
