### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by TheRealMkadmi** [aio-libs/aiomonitor#415]
### Describe the bug

When running on windows: `python -m aiomonitor.cli`, the following exception is thrown: `ModuleNotFoundError: No module named 'fcntl'`

### To Reproduce

`python -m aiomonitor.cli` on Windows

### Expected behavior

Console monitor shows up. 

### Logs/tracebacks

```python-traceback
python -m aiomonitor.cli
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Wahib\Desktop\Workbench\repos\cpanel-cracker\venv\Lib\site-packages\aiomonitor\cli.py", line 5, in <module>
    from .telnet import TelnetClient
  File "C:\Users\Wahib\Desktop\Workbench\repos\cpanel-cracker\venv\Lib\site-packages\aiomonitor\telnet.py", line 5, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

### Python Version

```console
Python 3.11.0
```

### aiomonitor Version

```console
Name: aiomonitor
Version: 0.7.1
Summary: Adds monitor and Python REPL capabilities for asyncio applications
Home-page: https://github.com/aio-libs/aiomonitor
Author: Nikolay Novik
Author-email: nickolainovik@gmail.com
License: Apache-2.0
Location: C:\Users\Wahib\Desktop\Workbench\repos\cpanel-cracker\venv\Lib\site-packages
Requires: aioconsole, aiohttp, attrs, click, janus, jinja2, prompt-toolkit, telnetlib3, terminaltables, trafaret, typing-extensions
Required-by:
```

### OS

Windows

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
Based on Windows not being present in CI and the only Trove classifier from the OS category is POSIX, I'd say that it was never intended to be supported. So this is not a bug but maybe a documentation opportunity, as there's not many places one can deduce the supported platforms from, it seems.

But if @achimnol were to be open to adding support (making this a feature request), you @TheRealMkadmi would have to send a PR with both fallbacks for non-POSIX environments and test coverage (pytest + CI matrix).

**Comment by achimnol** [comment]
I'm open to have Windows support as long as it does not incur significant maintenance efforts.

The telnet interface is a very minimal one and probably should be replaced with more structured API with separate client-side TUI.

I'll try some AI-assisted approaches to achieve this. Or, contributions are also welcome!
